[[mysterygift]]
name = "celebi"
giftType = "Pokemon"
beginningDate = "2024-07-11 11:02:35.882827"
endDate = "2024-07-12 11:04:58.331731"

[mysterygift.pokemongift]
originalTrainer = "test"
id = 251
species = "celebi"
nickname = "celebi"
shiny = false
locationOfOrigin = "Johto"
types = ["Grass"]
abilites = ["Overgrowth"]
stats = [10, 10, 10, 10, 10, 10, 10]
moves = ["", "", "", ""]
